repos:
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.426.0
    hooks:
      - id: renovate-config-validator
    # TODO: sandbox Deno
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt
      - id: deno-lint
    # TODO: run deno check
  - repo: local
    hooks:
      - id: run
        name: build k8s manifest
        entry: bash -c 'cd cdk8s/ && deno task build'
        language: system
        types: [ts]
        pass_filenames: false
