on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad@sha256:7f2a44db87a837ef0a09801d8a06d2343bf8ed266f2b977b336136a74f6639d7

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
