on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad@sha256:1ddd51defcc92549f57326eef9e6568a44ba8c39259063c2942a4167a13180da

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
