- id: "1646520147690"
  alias: Auto-lock the front door
  description: Lock the front door when it has been open for too long
  trigger:
    - platform: state
      entity_id:
        - lock.front_door
      to: unlocked
      for:
        hours: 0
        minutes: 30
        seconds: 0
      alias: When the front door has been unlocked for 30 minutes
  condition:
    - condition: state
      entity_id: binary_sensor.front_door_open
      state: "off"
      for:
        hours: 0
        minutes: 30
        seconds: 0
      alias: Check that the door hasn't been opened in the last 30 minutes
  action:
    - data: {}
      target:
        entity_id: lock.front_door
      alias: Lock the door
      action: lock.lock
  mode: single
