- id: "1723005544437"
  alias: Bedroom AC
  description: ""
  trigger:
    - platform: time
      at: 02:00:00
  condition: []
  action:
    - parallel:
        - metadata: {}
          data: {}
          target:
            device_id: 68c59fd90156ba5f662683070f4ce535
          action: climate.turn_off
        - alias: Toggle fan
          sequence:
            - action: switch.turn_off
              metadata: {}
              data: {}
              target:
                device_id: ad43b428586465e989e3c730c1310b7f
            - delay:
                hours: 0
                minutes: 0
                seconds: 5
                milliseconds: 0
            - action: switch.turn_on
              metadata: {}
              data: {}
              target:
                device_id: ad43b428586465e989e3c730c1310b7f
  mode: single
