- id: "1646198210838"
  alias: Brighten bollards on motion
  description: Brighten bollards when motion is detected outside
  triggers:
    - alias: Motion has been detected outside
      entity_id:
        - binary_sensor.outdoor_motion
      to: "on"
      for:
        hours: 0
        minutes: 0
        seconds: 1
      trigger: state
  conditions:
    - alias: All of
      condition: and
      conditions:
        - condition: or
          conditions:
            - alias: Awake
              condition: or
              conditions:
                - condition: state
                  entity_id: input_boolean.awake
                  state: "on"
            - alias: Motion has been consistent and asleep
              condition: and
              conditions:
                - alias: Motion has been detected for at least two seconds
                  condition: state
                  entity_id: binary_sensor.outdoor_motion
                  for:
                    hours: 0
                    minutes: 0
                    seconds: 2
                  state: ""
                - condition: state
                  entity_id: input_boolean.awake
                  state: "off"
        - condition: state
          entity_id: input_boolean.sun_is_down
          state: "on"
          alias: Sun is down
  actions:
    - action: scene.turn_on
      metadata: {}
      target:
        entity_id: scene.bollards_bright
    - delay:
        hours: 0
        minutes: 2
        seconds: 0
        milliseconds: 0
    - if:
        - condition: state
          entity_id: input_boolean.sun_is_down
          state: "on"
      then:
        - action: scene.turn_on
          target:
            entity_id: scene.bollards_dimmed
          data:
            transition: 10
      else:
        - data:
            transition: 10
          action: light.turn_off
          target:
            entity_id:
              - light.front_bollards
              - light.side_bollards
  mode: parallel
  max: 1000
