- id: "1723005544438"
  alias: Coming Home
  description: When getting near my house
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.near_home
      event: enter
      alias: Jerred is near home
  condition:
    - condition: state
      entity_id: input_boolean.enable_heater
      state: "on"
      alias: Heater is enabled
  action:
    - alias: Set heater temperature
      data:
        hvac_mode: heat
        temperature: "{{ states('input_number.day_temperature') }}"
      target:
        entity_id: climate.dining_room
      action: climate.set_temperature
  mode: single
