- id: "1664593118148"
  alias: Good Night
  description: ""
  triggers:
    - event_type: ios.action_fired
      event_data:
        actionID: A91A15AA-479E-416C-8F51-BD983A999266
      context: {}
      trigger: event
    - entity_id:
        - binary_sensor.flic_80e4da7a367a
      trigger: state
  conditions: []
  actions:
    - action: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.awake
    - parallel:
        - alias: Turn off bedroom lights
          action: scene.turn_on
          target:
            entity_id: scene.bedroom_dimmed
          data:
            transition: 10
        - alias: Play rain sounds
          if:
            - condition: template
              value_template: "true"
          then:
            - data: {}
              target:
                area_id: bedroom
              action: media_player.unjoin
            - data:
                volume_level: 0
              target:
                area_id: bedroom
              action: media_player.volume_set
            - target:
                entity_id: media_player.bedroom
              data:
                media_content_id: FV:2/7
                media_content_type: favorite_item_id
              metadata:
                title: Rain
                thumbnail: https://sonosradio.imgix.net/station-images/67e41092-f0d4-428b-ba56-b58e0b685f7f.png?w=200&auto=format,compress
                media_class: genre
                children_media_class:
                navigateIds:
                  - {}
                  - media_content_type: favorites
                    media_content_id: ""
                  - media_content_type: favorites_folder
                    media_content_id: object.item.audioItem.audioBroadcast
              action: media_player.play_media
            - repeat:
                count: 5
                sequence:
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                  - action: media_player.volume_up
                    metadata: {}
                    data: {}
                    target:
                      entity_id: media_player.bedroom
              alias: Gradually increase volume
        - if:
            - condition: state
              entity_id: input_boolean.enable_heater
              state: "on"
          then:
            - data:
                hvac_mode: heat
                temperature: "{{ states('input_number.night_temperature') }}"
              enabled: true
              target:
                device_id: b39077ee57bc3f2671ad264ec15b72a7
              action: climate.set_temperature
          alias: Set the heater
        - alias: Turn off holiday lights
          if:
            - condition: state
              entity_id: input_boolean.holiday_lights_enabled
              state: "on"
          then:
            - action: light.turn_off
              metadata: {}
              data: {}
              target:
                device_id: 4ab21b6cc4c70a663a22a9ad8cea1db1
            - action: light.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: light.christmas_tree
        - alias: Turn off front porch lights
          action: switch.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: switch.patio_lights
  mode: single
