- id: "1664593118148"
  alias: Good Night
  description: Turn off lights, play rain sounds, and set the heater
  triggers:
    - event_type: ios.action_fired
      event_data:
        actionID: A91A15AA-479E-416C-8F51-BD983A999266
      context: {}
      trigger: event
      alias: iOS action fired
    - entity_id:
        - binary_sensor.flic_80e4da7a367a
      trigger: state
      alias: Flic button pressed
  conditions: []
  actions:
    - action: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.awake
      alias: Turn off awake boolean
    - parallel:
        - alias: Dim bedroom lights
          if:
            - condition: state
              entity_id: light.bedroom
              state: "on"
              alias: Bedroom lights are on
          then:
            - action: scene.turn_on
              target:
                entity_id: scene.bedroom_dimmed
        - alias: Play rain sounds
          if:
            - condition: template
              value_template: "true"
              alias: Always true
          then:
            - data: {}
              target:
                area_id: bedroom
              action: media_player.unjoin
              alias: Unjoin media player
            - data:
                volume_level: 0
              target:
                area_id: bedroom
              action: media_player.volume_set
              alias: Set volume to 0
            - target:
                entity_id: media_player.bedroom
              data:
                media_content_id: FV:2/7
                media_content_type: favorite_item_id
              metadata:
                title: Rain
                thumbnail: https://sonosradio.imgix.net/station-images/67e41092-f0d4-428b-ba56-b58e0b685f7f.png?w=200&auto=format,compress
                media_class: genre
                children_media_class:
                navigateIds:
                  - {}
                  - media_content_type: favorites
                    media_content_id: ""
                  - media_content_type: favorites_folder
                    media_content_id: object.item.audioItem.audioBroadcast
              action: media_player.play_media
              alias: Play rain sounds
            - repeat:
                count: 5
                sequence:
                  - delay:
                      hours: 0
                      minutes: 0
                      seconds: 5
                      milliseconds: 0
                  - action: media_player.volume_up
                    metadata: {}
                    data: {}
                    target:
                      entity_id: media_player.bedroom
                    alias: Increase volume
              alias: Gradually increase volume
        - if:
            - condition: state
              entity_id: input_boolean.enable_heater
              state: "on"
              alias: Heater enabled
          then:
            - data:
                hvac_mode: heat
                temperature: "{{ states('input_number.night_temperature') }}"
              enabled: true
              target:
                entity_id: climate.dining_room
              action: climate.set_temperature
              alias: Set heater temperature
          alias: Set the heater
        - alias: Turn off holiday lights
          if:
            - condition: state
              entity_id: input_boolean.holiday_lights_enabled
              state: "on"
              alias: Holiday lights enabled
          then:
            - action: light.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: light.porch_festiva_lights
              alias: Turn off christmas tree lights
            - action: light.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: light.christmas_tree_lights
              alias: Turn off Christmas tree
        - alias: Turn off front porch lights
          action: switch.turn_off
          metadata: {}
          data: {}
          target:
            entity_id: switch.patio_lights
  mode: single
