- id: "1647291929910"
  alias: Leaving Home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.home
      event: leave
      alias: Jerred leaves home
  condition: []
  action:
    - data: {}
      target:
        entity: lock.front_door
      alias: Lock the front door
      action: lock.lock
    - if:
        - condition: state
          entity_id: input_boolean.enable_heater
          state: "on"
          alias: Heater is enabled
      then:
        - enabled: true
          data:
            temperature: "{{ states('input_number.away_temperature') }}"
          target:
            entity_id: climate.dining_room
          action: climate.set_temperature
          alias: Set heater temperature
      alias: Set the heater
    - alias: Turn on the Roomba
      if:
        - condition: time
          before: "19:00:00"
          after: 07:00:00
          alias: Within Roomba operating hours
      then:
        - data: {}
          target:
            entity_id: vacuum.roomba_combo
          action: vacuum.start
          alias: Start Roomba
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.sonoff_1002166461
      alias: Turn off espresso machine
  mode: single
