- id: "1727532905322"
  alias: Noon
  description: ""
  trigger:
    - platform: time
      at: "12:00:00"
      alias: Noon
  condition: []
  action:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.espresso_machine
      alias: Turn off Sonoff switch
  mode: single
