- id: "1646197051085"
  alias: Outdoor lights (sunset)
  description: ""
  triggers:
    - entity_id:
        - input_boolean.sun_is_down
      to: "on"
      from: "off"
      trigger: state
      alias: Sun is down
  conditions: []
  actions:
    - data:
        transition: 30
      target:
        area_id:
          - balcony
          - backyard
      action: light.turn_on
      alias: Turn on balcony and backyard lights
    - action: scene.turn_on
      target:
        entity_id: scene.bollards_dimmed
      data: {}
      alias: Turn on bollards dimmed scene
    - if:
        - condition: state
          entity_id: input_boolean.holiday_lights_enabled
          state: "off"
          alias: Holiday lights disabled
      then:
        - data: {}
          target:
            entity_id: light.patio_lights
          action: light.turn_on
          alias: Turn on patio lights
      else:
        - action: scene.turn_on
          data: {}
          target:
            entity_id: >
              {{ [ 'scene.front_porch_crystalline', 'scene.front_porch_golden_star', 'scene.front_porch_snow_sparkle', 'scene.front_porch_under_the_tree' ] | random }}
          alias: Turn on random front porch scene
  mode: single
