- id: "1646197080067"
  alias: Outdoor lights (sunrise)
  description: ""
  trigger:
    - platform: state
      entity_id:
        - input_boolean.sun_is_down
      to: "off"
      from: "on"
      alias: Sun is up
  condition: []
  action:
    - data:
        transition: 30
      target:
        area_id:
          - balcony
          - front_porch
          - backyard
          - front_path
          - side_path
      action: light.turn_off
      alias: Turn off outdoor lights
  mode: single
