- id: "1658527628923"
  alias: Outdoor lights (midnight)
  description: ""
  trigger:
    - platform: time
      at: 00:00:00
      alias: Midnight
  condition: []
  action:
    - action: input_boolean.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.awake
      alias: Turn off awake boolean
    - data: {}
      target:
        area_id:
          - backyard
        entity_id:
          - light.lower_string_lights
          - light.porch_rail_lights
      action: light.turn_off
      alias: Turn off backyard lights
  mode: single
