- id: "1666932468043"
  alias: Sunrise
  description: ""
  trigger:
    - platform: sun
      event: sunrise
      offset: "0"
      alias: Sunrise event
  condition: []
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sun_is_down
      alias: Turn off sun_is_down boolean
  mode: single
