- id: "1673758217687"
  alias: Turn off garage lights
  description: ""
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hue_motion_sensor_1_motion
      to: "off"
      for:
        hours: 0
        minutes: 5
        seconds: 0
      alias: Motion stopped in garage
  condition: []
  action:
    - repeat:
        until:
          - condition: state
            entity_id: binary_sensor.hue_motion_sensor_1_motion
            state: "off"
            for:
              hours: 0
              minutes: 7
              seconds: 0
            alias: No motion for 7 minutes
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
    - data:
        transition: 10
      target:
        area_id: garage
      action: light.turn_off
      alias: Turn off garage lights
  mode: single
