- id: "1647291874140"
  alias: Welcome Home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.jerred
      zone: zone.home
      event: enter
  condition: []
  action:
    - data: {}
      target:
        device_id: f218df4be34c06c62559ae599f5f735e
      alias: Unlock the front door
      action: lock.unlock
    - alias: Turn on lights
      action: scene.turn_on
      target:
        entity_id: scene.dining_room_bright
      data: {}
    - if:
        - condition: state
          entity_id: input_boolean.enable_heater
          state: "on"
      then:
        - data:
            temperature: "{{ states('input_number.day_temperature') }}"
          enabled: true
          target:
            device_id: b39077ee57bc3f2671ad264ec15b72a7
          action: climate.set_temperature
      alias: Set the heater
    - alias: Brighten the Bollards
      if:
        - condition: state
          entity_id: input_boolean.sun_is_down
          state: "on"
      then:
        - alias: Brighten Bollards
          action: scene.turn_on
          target:
            entity_id: scene.bollards_bright
          data: {}
        - delay:
            hours: 0
            minutes: 2
            seconds: 0
            milliseconds: 0
        - alias: Dim Bollards
          action: scene.turn_on
          data: {}
          target:
            entity_id: scene.bollards_dimmed
    - alias: Send Roomba home
      if:
        - condition: and
          conditions:
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba_combo
                  attribute: status
                  state: Charging
              alias: Roomba is not charging
            - condition: not
              conditions:
                - condition: state
                  entity_id: vacuum.roomba_combo
                  attribute: status
                  state: Docked
              alias: Roomba is not docked
          alias: Roomba is not docked or charging
          enabled: true
      then:
        - data: {}
          target:
            device_id: fac32b67dd63fdcdf98f51db9c9c1c6e
          alias: Send the Roomba home
          action: vacuum.return_to_base
  mode: single
