- id: "1733021748186"
  name: Christmas Tree
  entities:
    light.christmas_tree:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
        - color_temp
        - xy
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2702
      color_temp: 370
      hs_color:
        - 28.391
        - 65.659
      rgb_color:
        - 255
        - 166
        - 87
      xy_color:
        - 0.526
        - 0.387
      is_hue_group: true
      hue_scenes: []
      hue_type: room
      lights:
        - Christmas Tree
      entity_id:
        - light.festavia_string_lights_1_2
      dynamics: false
      icon: mdi:lightbulb-group
      friendly_name: Christmas Tree
      supported_features: 40
      state: "on"
  metadata: {}
  icon: mdi:pine-tree
  alias: Christmas Tree Scene
