db:
  dbname: invidious
  user: postgres
  # not exposed to outside of the cluster, so this should be OK
  # ideally this should be a secret
  password: "orJ.U8QskAB3szvUK-8*"
  host: "<POSTGRES HOST>"
  port: 5432
check_tables: true
hmac_key: "f.3_RvweD9yDyxnfvgfA"
