
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad@sha256:a10407a4c75058c7df1b83957de9be47cca93599fdbf7353aafa4918a10fe2bc

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
