on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad@sha256:09a680450765a92053403e2867d1ced1a36d6ea98aef21f6c90cbab8db983af4

      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
