name: Dagger
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: |
          cd /usr/local
          curl -L https://dl.dagger.io/dagger/install.sh | sh
