name: Earthly CI

on:
  push:
  pull_request:

jobs:
  earthly-job:
    runs-on: [earthly-satellite#lamport]
    env:
      FORCE_COLOR: 1
      EARTHLY_TOKEN: "${{ secrets.EARTHLY_TOKEN }}"
    steps:
      - uses: actions/checkout@v2
      - name: Earthly build
        run: earthly -ci +build
