name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: pre-commit/action@v3.0.0
        continue-on-error: true
      - uses: reviewdog/action-suggester@v1
