name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

permissions: write-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: pre-commit/action@v3.0.0
      - uses: gr2m/create-or-update-pull-request-action@v1
        if: always() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "chore: fix pre-commit"
          author: "pre-commit <pre-commit@sjer.red>"
          branch: ${{ github.head_ref }}
